name: Django application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "sreenathreddy07" --password-stdin
        docker image build -t sreenathreddy07/dockerswarm_jenkins_k8s:latest .
        docker push sreenathreddy07/dockerswarm_jenkins_k8s:latest
